### ISSUE TITLE
Metagenomics_Analysis miniproject

### ISSUE THREAD

**Issue by karegapauline** [bioinformatics-hub-ke/BOSS-miniprojects#3]
[Metagenomics_Analysis](https://github.com/bioinformatics-hub-ke/BOSS-miniprojects/tree/main/Metagenomic_Analysis)

**Comment by sebymusundi** [comment]
Hello, I am interested in taking part in the above analysis. It provides an opportunity to create various pipelines, get data and compare with the existing published works. It is also an opportunity to develop newer pipelines and check if the use of different tools would provide similar results.  I believe i will significantly gain practical skills by being part of the above group.

**Comment by Faith-98** [comment]
Metagenomics is broad and presents many research opportunities. By taking part in this project, I will have the chance to explore the various tools that could be applied in metagenomics.

**Comment by karegapauline** [comment]
@Marthariv I am interested in gaining metagenomics data analysis skills . This metagenomic mini project present a great opportunity to achieve this

**Comment by wadegumeshack** [comment]
Metagenomics offers insightful approaches in research enabling scientists to determine myriad pathogens from a 'single pool' that could lead to 
-pathogen discovery, 
-determination of multiple infections arising from different pathogens within the same host 
-mapping of different pathogens to their respective vectors.
The work accomplished in this publication in the preliminary molecular analyses and subsequent bioinformatics analyses is revolutionary in arbovirus research especially in regions not well resourced with regard to medical research funding.
Coming from an acute respiratory viruses research background, I intend to apply the tools used in this study to determine instances of co-circulation of coronaviruses and other viral etiologies and the implication on disease severity.

**Comment by aakilkhanemon** [comment]
I have the expertise and research interest in bacterial and viral uncharacterized protein's molecular computational characterization, functional annotations, phylogenetic analysis, multiple sequence analysis, physicochemical analysis, sequence alignment, gene Identification, genome assembly, protein structure alignment, protein structure (2D and 3D) prediction, protein-protein interactions, genome-wide association studies, modelling of evolution. subcellular localization analysis, conserved domain analysis, motif, protein folding, coil, superfamily identification, model quality assessment, active site determination etc. Also gained projects experience with drug designing studies against human pathogenic infectious viruses and bacteria. Having hands-on experience with MEGA, Discovery Studio, PyMoL, Autodock tools(Vina, PyRx), Open Babel, Swissmodel, RaptorX, Galaxy, NCBI, UniProt, RSCB, LaTex, MS office, Mendeley, Endnote etc. I heartily believe that this mini-project will be so much helpful and will play a significant role in my molecular genomics, microbial data analysis research by using several bioinformatics knowledge and exploring projects about that particular field. Focus to obtain a research opportunity to utilize biosciences techniques, knowledge, computational biology tools to develop & implement bioinformatics applications & analysis programs and research prospects.

**Comment by florahnaks** [comment]
I am interested in taking part in this project as it will help me gain hands on experience on how to go about metagenomics research with the already acquired skills.

**Comment by cynthiaawuor3** [comment]
I am a MSc bioinformatics student and working in research laboratory doing a lot sequencing. Although i have no experience in metagenomics studies ,i am interested in being part of the training. Learning metagenomics analysis will broaden my research interests and i am ready to gain a lot of skills from this training that i will be so much glad to learn. I have experience analyzing RNASeq and viral genomes using linux/Unix and one of your objective being using tools and learning alternatives that can be used in the pipeline really excites me.I am really looking forward on taking the training and looking forward for your response.

**Comment by otenga-bit** [comment]
Viral vectors are notorious in disease transmission and understanding their genome and their characterization inspires me.

**Comment by jmajanja** [comment]
I am interested in taking part in this project because it is relevant to the work that I am currently doing. My PhD project is focused on pathogen discovery from mosquito samples. In my study, I am using viral  culture followed by genome sequencing to detect uncharacterized viruses in mosquito pools. I have recently been trained on next generation sequence analysis using linux and this will add on to the repertoire of skills that are necessary for me to complete my PhD project successfully. I look forward to being part of this exciting opportunity.

**Comment by karegapauline** [comment]
Dear @sebymusundi , @wadegumeshack , @jmajanja , @florahnaks , @Faith-98 and @Marthariv, welcome to the Metagenomic Analysis mini project team. Kindly respond by sending an email to bioinformaticshubofkenya@gmail.com confirming your acceptance to this invite. 
We look forward to hearing from you. 😃 . Congratulations.

**Comment by sebymusundi** [comment]
Hello,

Confirming my acceptance to the metagenomics analysis mini project team.

Regards.
Musundi Sebastian

**Comment by jmajanja** [comment]
Hi,
This is my confirmation of acceptance to be part of the metagenomics
analysis project team.
Regards
Janet Majanja

**Comment by florahnaks** [comment]
Thank you so much for the opportunity.
I confirm my acceptance for participation.


Florence.

**Comment by karegapauline** [comment]
@sebymusundi , @wadegumeshack , @jmajanja , @florahnaks , @Faith-98 and @Marthariv,

Dear participant,

Congratulations. You have been selected to participate in the 3rd Phase of BOSS events: Viral Mini project/Metagenomics/Open science/ Data Handbook/Plant genomics. We are inviting you for a virtual meeting on 1st December 2021 at 1600hrs to 1700hrs with the following agenda:

1. Introduction of Participants

2. Meeting up with your respective mentors

3. Time and Deadlines

4. Selecting mini project team leads

5. Discuss on the way forward

AoB


This is a mandatory meeting, so kindly join on time. Find the link to the zoom meeting below. We look forward to seeing you.



BHKI is inviting you to a scheduled Zoom meeting.

Topic: BOSS Mini Projects Introduction meeting
Time: Dec 1, 2021 04:00 PM Nairobi

Join Zoom Meeting
https://us02web.zoom.us/j/86411432009?pwd=d0h0dVhUSGZoL3VNM2dPYktnbXR2QT09

Meeting ID: 864 1143 2009
Passcode: 611959

Warm Regards,

David Kiragu
On behalf of the BHKi and Open ScienceKE teams

**Comment by jmajanja** [comment]
Good morning, 
Unfortunately I missed the introductory meeting. Kindly advise.

regards,
Janet
