### ISSUE TITLE
OpenScience_RDM_handbook

### ISSUE THREAD

**Issue by karegapauline** [bioinformatics-hub-ke/BOSS-miniprojects#4]
[OpenScience_RDM_handbook](https://github.com/bioinformatics-hub-ke/BOSS-miniprojects/tree/main/OpenScience_RDM_handbook)

**Comment by Wahura** [comment]
Good research data management is the backbone for increasing research efficiency, enabling data security and safety, making research outputs more visible and enabling collaborations. I am interested in this project because I would like to gain more knowledge on research data management. The prospects of gaining insights on how good research data management can be attained in resource constrained settings is exciting to me. In addition, I am enthusiastic about implementing the FAIR principle during the implementation of this project. This project will also provide a platform for me to collaborate with the other members interested in the project.

**Comment by mubangansofu** [comment]
RDM is a broad area and I would like to learn on this project as we tug along

**Comment by karegapauline** [comment]
Dear @Wahura @mubangansofu @otenga-bit @aakilkhanemon, and @Rissy2021 welcome to the Open Science Research Handbook team. Kindly respond by sending an email to bioinformaticshubofkenya@gmail.com confirming your acceptance to this invite. 
We look forward to hearing from you. :-)

**Comment by otenga-bit** [comment]
Dear Karega Pauline,
In response to the above subject. This mini-project was not my interest. If
I can get a chance in either viral analysis, metadata analysis or plant
genome analysis, I'll appreciate. If not I can just take up this one.

Regards,
Felix Otenga

**Comment by karegapauline** [comment]
@otenga-bit, unfortunately, the other projects have full teams. If you don't mind staying on this project, please stay on.

**Comment by otenga-bit** [comment]
Hello Karega,

I'll be glad to take part in the project. Thank you for the opportunity.

**Comment by aakilkhanemon** [comment]
Dear Karega Pauline, 

This is my confirmation of acceptance to be part of the BOSS mini project on the open science research management team.
I have shown interest in basically any one of viral analysis, metagenomics analysis or plant genome analysis, This mini-project about open science research management was not my interest. I am highly requesting to you sir, if possible or create any vacancy on the viral analysis, metagenomics or plant genomics team please add me on there as a member. I will be so grateful to you if I will be there either viral, meta genomic or plant genomics project team.
I'll be glad to take part in the project. Thank you for the opportunity.

Sincerely,
Mohammed Emon

**Comment by mubangansofu** [comment]
Dear Pauline,

This is my confirmation of acceptance and participation in this port of the BOSS mini project


Mubanga

**Comment by karegapauline** [comment]
Kindly send an email to ***@***.*** to enable easier
communication

**Comment by otenga-bit** [comment]
Hello,

I was not able to join the meeting. Can I get a link to the recording of
the meeting, if there was.
Regards.

**Comment by karegapauline** [comment]
@otengabit send an email to ***@***.***

It'll make communication much easier

**Comment by otenga-bit** [comment]
Hello, Pauline Karega,
I was not able to attend a meeting for the mini-project i was assigned.
Kindly connect me to the group leader so that I can participate. I'll
appreciate your response and guidance.
Regards,
Felix Otenga

**Comment by karegapauline** [comment]
@otenga-bit I sent a message that you should send an email to bioinformaticshubofkenya@gmail.com to make communication easier. Kindly do so as son as you can

**Comment by mubangansofu** [comment]
Please also send email to ***@***.*** for
easier communication
