### ISSUE TITLE
OpenScience_in_Africa

### ISSUE THREAD

**Issue by karegapauline** [bioinformatics-hub-ke/BOSS-miniprojects#5]
[OpenScience_in_Africa](https://github.com/bioinformatics-hub-ke/BOSS-miniprojects/tree/main/OpenScience_in_Africa)

**Comment by cynthiaawuor3** [comment]
Being part of the bioinformatics community in Kenya and Africa.Getting a forum where we can talk about the challenges we are faced with and looking for solutions would be something of my interest and make me so interested in openscience forum.I would love to join the training and learn from experienced bioinformaticians.

**Comment by JGisaina** [comment]
Open science is one of the pillars of innovations. Open science promotes active participation of ambitious individuals in scientific forum without barriers .   In africa open science will promote the establishment of robust scientfic network, promotes innovations and definately improve standards of living. I am glad to be part of the team implementing open science for better Africa.

**Comment by mubangansofu** [comment]
Science is one of the engine rooms of development and looking at Africa's young population presents alot of promise to improve the welfare of people on our beautiful continent. By participating on this project, I will be contributing in a small way to the betterment of the continent and her people.

**Comment by karegapauline** [comment]
@serahed 
I would like to actively participate in this project as it will give me an opportunity to dive in deeper into open science especially the state of awareness about the topic in Kenya. Through the research and literature reading I will also be able to understand the topic better and hence be able to create opportunities around me to have such conversations. I am also very good at literature research and writing, hence know I can successfully be able to help the team in writing and research relating to the topic.

**Comment by karegapauline** [comment]
Dear @JGisaina @serahed @cynthiaawuor3 @Rehemashungu and @swatiri, welcome to the Open Science in Africa team. 
Kindly respond by sending an email to bioinformaticshubofkenya@gmail.com confirming your acceptance to this invite. 
We look forward to hearing from you. 😃 . Congratulations.

**Comment by JGisaina** [comment]
I confirm my participation
Regards

**Comment by karegapauline** [comment]
@JGisaina @serahed @cynthiaawuor3 @Rehemashungu and @swatiri

Congratulations. You have been selected to participate in the 3rd Phase of BOSS events: Viral Mini project/Metagenomics/Open science/ Data Handbook/Plant genomics. We are inviting you for a virtual meeting on 1st December 2021 at 1600hrs to 1700hrs with the following agenda:

1. Introduction of Participants

2. Meeting up with your respective mentors

3. Time and Deadlines

4. Selecting mini project team leads

5. Discuss on the way forward

AoB


This is a mandatory meeting, so kindly join on time. Find the link to the zoom meeting below. We look forward to seeing you.



BHKI is inviting you to a scheduled Zoom meeting.

Topic: BOSS Mini Projects Introduction meeting
Time: Dec 1, 2021 04:00 PM Nairobi

Join Zoom Meeting
https://us02web.zoom.us/j/86411432009?pwd=d0h0dVhUSGZoL3VNM2dPYktnbXR2QT09

Meeting ID: 864 1143 2009
Passcode: 611959

Warm Regards,

David Kiragu
On behalf of the BHKi and Open ScienceKE teams
