### ISSUE TITLE
PlantGenome_Assembly

### ISSUE THREAD

**Issue by karegapauline** [bioinformatics-hub-ke/BOSS-miniprojects#6]
[PlantGenome_Assembly](https://github.com/bioinformatics-hub-ke/BOSS-miniprojects/tree/main/PlantGenome_Assembly)

**Comment by Oscar857-dotcom** [comment]
Plant genetics has always piqued my interest as a plant scientist. I am fascinated by the application of bioinformatics skills in areas such as DNA sequencing, genome assembly, and genome annotation to understand the genome of a plant. I can use this attained knowledge and skills to locate potential genes that can be engineered to boost yield, drought tolerance, and pest and disease resistance, thereby addressing the larger issue of food security more less as a result of climate change.  This project, I believe, is a fantastic fit for me to get these abilities and expertise.

**Comment by AMBUTSI** [comment]
I have always been fascinated by genome assembly initiatives with the aim of identifying putative protein-coding genes. Besides, I love understanding the genetic basis of different phenotypic characteristics. I would also love to learn and understand how to annotate genes and predict their functions using different prediction models. Participating in this project will equip me with useful skills and expertise to answer different biological questions based on an organism's genetic makeup.

**Comment by NOngeso** [comment]
Biological data science analysis in plant and soil health is under-explored, yet it accounts for approximately 50% of biodiversity. I look forward to gaining skills to generate knowledge that will fill in the gaps and innovate new biodiversity conservation tools and enhance food security.

**Comment by swatiri** [comment]
Food security is most critical in low-income, food-deficit countries such as Kenya. Possible solutions include employing technologies that improve disease resistance and building more robust crop varieties as seen in plant genomics in agriculture. I have always aspired to be at the forefront of the fight against food insecurity in the country. I look forward to gaining skills that help me realize this dream.

**Comment by kenmurithi** [comment]
Having worked and gained skills on genome assembly and on DNA sequence pre-processing steps, I feel the crucial step left for me is to perform genome annotation. I see this project offering a perfect opportunity for me to 1.  Garner skills in genome annotation  2. Venture into scientific paper reproducibility 3. Interact, network, and work together with fellow scientists as we work through the mini-project.

**Comment by Shizler** [comment]
As a beginner in Bioinformatics, this project will help me understand genome sequencing,assembly and annotation.I would later use the skills learnt to study the genome of purple tea which has recently gained popularity due to its health benefits.

**Comment by Kevin-Cissie** [comment]
70% of my undergraduate degree has revolved around Plant biology with an larger portion in plant biotechnology. This project is fit for me as well appropriate for growing and developing my skills in the field as a bioinformatics beginner

**Comment by cynthiaawuor3** [comment]
I am a MSc bioinformatics student and working in research laboratory doing a lot molecular work.I have huge interest i plant genome analysis and learning plant genome assembly is one of them,i would really love to attend the training and learn more about the tools used for plant genome assembly. I am really looking forward on taking the training and looking forward for your response.

**Comment by Nyasita** [comment]
I am interested in this project because I would like to garner skills in genome annotation and paper reproducibility. Also, it is a great way to work as a team and share skills.

**Comment by otenga-bit** [comment]
This project will enhance my knowledge and skills. An inspiration that stems in genome assembly and learning of gene annotations. Taking part in this project will be an honor.

**Comment by gashanjakim** [comment]
Hello!, I would like to be considered for PlantGenome_Assembly mini-project. I have another project I'm working on currently, that is related to this. Hence, participating in this mini-project will assist me to acquire more skills that will enable me to be efficient and effective in my project. Kind regard.

**Comment by karegapauline** [comment]
Dear @kenmurithi , @Nyasita , @gashanjakim , @Oscar857-dotcom , and @NOngeso , welcome to the plant genome assembly mini project team. Kindly respond by sending an email to bioinformaticshubofkenya@gmail.com by Monday Nov 29 at 10:00am EAT confirming your acceptance to this invite. 
We look forward to hearing from you. 😃 . Congratulations.

**Comment by karegapauline** [comment]
Dear @kenmurithi , @Nyasita , @gashanjakim , @Oscar857-dotcom , @swatiri and @NOngeso

Congratulations. You have been selected to participate in the 3rd Phase of BOSS events: Viral Mini project/Metagenomics/Open science/ Data Handbook/Plant genomics. We are inviting you for a virtual meeting on 1st December 2021 at 1600hrs to 1700hrs with the following agenda:

1. Introduction of Participants

2. Meeting up with your respective mentors

3. Time and Deadlines

4. Selecting mini project team leads

5. Discuss on the way forward

AoB


This is a mandatory meeting, so kindly join on time. Find the link to the zoom meeting below. We look forward to seeing you.



BHKI is inviting you to a scheduled Zoom meeting.

Topic: BOSS Mini Projects Introduction meeting
Time: Dec 1, 2021 04:00 PM Nairobi

Join Zoom Meeting
https://us02web.zoom.us/j/86411432009?pwd=d0h0dVhUSGZoL3VNM2dPYktnbXR2QT09

Meeting ID: 864 1143 2009
Passcode: 611959

Warm Regards,

David Kiragu
On behalf of the BHKi and Open ScienceKE teams
