### ISSUE TITLE
Viral_Analysis

### ISSUE THREAD

**Issue by karegapauline** [bioinformatics-hub-ke/BOSS-miniprojects#7]
[Viral_Analysis](https://github.com/bioinformatics-hub-ke/BOSS-miniprojects/tree/main/Viral_Analysis)

**Comment by OduorBetty** [comment]
My desire to become a well-rounded scientist includes genomic data analysis. I work as a medical microbiologist, and part of my job is sequencing and generating data. However, analyzing and interpreting the data is a struggle. My MSc research study is on sequencing and detecting the mutations associated with drug resistance, as part of antimicrobial resistance surveillance. I believe this project will equip with the necessary skills for data analysis.

**Comment by JGisaina** [comment]
Having intrest in RNA sequencing, the Viral RNA   analysis will help me develop skills required in variant calling,  assembly,  and other advanced RNAseq anaysis skills.  It will help jumpstart my career in genomic anaysis and biomarker development. Importantly, the skills will help me to efficiently accomplish the ongoing project that seeks to describe  genetic diversity of pfgdh genes in kenya.

**Comment by karegapauline** [comment]
@glado718
Doing viral analysis project using bioinformatics tools and pipeline will give me a platform to exercise and showcase my skills in the field of bioinformatics. I was also recently involved in drafting a manuscript for codeathon project entitled the genetic diversity of HIV-1 strains in Africa which used similar approaches. Hence, doing this project will help me practice and acquire skills that will be of great help in my career as a bioinformatician.

**Comment by Faith-98** [comment]
I have a major interest in molecular virology and plan to specialize in it as I advance my studies. This particular project will therefore help me understand the different platforms used in viral genome analysis. Also, I am part of a team that is doing research on Hep B virus, hence partaking in this mini-project will equip me with more skills, and I'll be able to contribute more to the study.

**Comment by Oronda** [comment]
With my undergraduate background in biotechnology, I am interested in participating in this mini project because from the aim of the project, I would be able to put into practice what I had learnt in the workshop like data preprocessing which involves quality control and also alignment which we had learnt in searching and sequence alignment session. With this project, I can be further exposed in the bioinformatics field. I have also been curious on how phylogenetics results are analysed and this happens to also be in the aim of the project. I am also interested to know how the pipeline that would be used in this project is similar or different to the galaxy that we learnt about in the workshop.

**Comment by cyrille88** [comment]
My research is focused on bat and rodent-borne emerging and re-emerging viral zoonotic pathogens of significant public health concern. In the course of my research, I did but Sanger sequencing, and over the last three years, I have been following training workshops on NGS sequencing and had the privilege to participate in a workshop on "Viral Genomics and Bioinformatics" organized by Wellcome Genome Campus at the University of Makerere in Uganda. For a couple of years, I have been serving as Teaching Assistant for the H3ABioNet where Introduction to Bioinformatics and Next Sequencing Bioinformatics are taught and practiced. However, I have never had the chance to be mentored, the raison d'etre for my interest in this mini-project. Thus, I will have the opportunity to be supervised by experts who shall guide me in reproducing the results of the "Phylogenetic Analysis of the 2020 West Nile Virus (WNV) Outbreak in Andalusia (Spain)". At the end of this phase, I will be able to confidently run NGS bioinformatics analysis and also to be able to develop my own pipelines for future research projects. Subsequently, I may also serve as a mentor to future trainees of the BOSS and would be also glad to serve in the Kenyan Bioinformatics Hub.

**Comment by Rehemashungu** [comment]
I did my bioinformatics studies during my third year and after graduating last year in BSc. Biotechnology and Laboratory science, I wanted to learn more of it hence I have been taking short courses to learn the basics. Participating in this project, I believe will put move me one step forward in my career.

**Comment by aakilkhanemon** [comment]
I have the expertise and research interest in bacterial and viral uncharacterized protein's molecular computational characterization, functional annotations, phylogenetic analysis, multiple sequence analysis, physicochemical analysis, sequence alignment, gene Identification, genome assembly, protein structure alignment, protein structure (2D and 3D) prediction, protein-protein interactions, genome-wide association studies, modelling of evolution. subcellular localization analysis, conserved domain analysis, motif, protein folding, coil, superfamily identification, model quality assessment, active site determination etc. Also gained projects experience with drug designing studies against human pathogenic infectious viruses and bacteria. Having hands-on experience with MEGA, Discovery Studio, PyMoL, Autodock tools(Vina, PyRx), Open Babel, Swissmodel, RaptorX, Galaxy, NCBI, UniProt, RSCB, LaTex, MS office, Mendeley, Endnote etc. I heartily believe that this mini-project will be so much helpful and will play a significant role in my molecular genomics, microbial data analysis research by using several bioinformatics knowledge and exploring projects about that particular field. Focus to obtain a research opportunity to utilize biosciences techniques, knowledge, computational biology tools to develop & implement bioinformatics applications & analysis programs and research prospects.

**Comment by florahnaks** [comment]
I am interested in taking part in this mini project to help me gain hands on experience and apply my RNA sequencing and analysis gained skills which will help me gain more expertise in viral genomics.

**Comment by cynthiaawuor3** [comment]
I am a MSc bioinformatics student and working in research laboratory doing a lot sequencing. ,i am interested in being part of the training. Learning viral  genomics analysis will broaden my research interests and i am ready to gain a lot of skills from this training that i will be so much glad to learn. I have experience analyzing RNASeq and viral genomes using linux/Unix and one of your objective being using tools and learning alternatives that can be used in the pipeline really excites me.I am really looking forward on taking the training and looking forward for your response.

**Comment by Gatheru-rose** [comment]
I am greatly interested in this viral mini project on Phylogenetic Analysis of the 2020 West Nile Virus (WNV) Outbreak in Andalusia (Spain) due to my strong passion for contributing to infectious disease research. I had the opportunity to be a bioinformatics intern at Icipe, where I learnt fundamental analysis skills of genomic data from preprocessing steps to coming up with relevant biological inferences using bioinformatics tools and resources. I would be thrilled to participate in this project to improve my skill set, receive mentorship, and network with other participants. This will eventually contribute to my research goals of contributing to infectious disease research through gaining a deeper understanding of the genetic basis of infectious diseases. I will appreciate an opportunity to discuss my research interest and look forward to a favorable response.

**Comment by Suenjuki** [comment]
My research interests were shaped by my initial research objectives of obtaining potential multivalent immunogenic epitopes for vaccine development for emerging ang re-emerging viral infections. Here I was able to identify B-cell and T-cell antigenic, immunogenic, non-allergenic epitopes that could be used to provide immunity across 24 viruses in study. Therefore, given an opportunity to be part of this project will increase my skills and improve my network. I will highly appreciate that.

**Comment by mudiboevans** [comment]
I am interested in the molecular epidemiology of pathogens including viruses. My previous research focused on understanding the genetic diversity and evolution mechanism of rotavirus A in coastal Kenya. I have had opportunities to perform phylogenetic analysis, however, this mini-project will give me a chance to cement on these skills, acquire new skills and establish collaborations. Thanks

**Comment by otenga-bit** [comment]
I am Felix Otenga. I have strong interest in bioinformatics and Genomics. This projects provides that opportunity to learn in- depth bioinformatics and practice the skills I have learnt. I'll be glad to take part in this mini project.

**Comment by mubangansofu** [comment]
I am an electrical engineer with a strong math and statistical background coupled with R skills. If I participate in the project, I want to understand if a non domain expert in bioinformatics and Genomics can actually leverage the data and draw insights despite no background in the two fields. That is the reason I am keen to take a stab

**Comment by karegapauline** [comment]
@Rissy2021
I am a Genomic scientists with a stong background in bioinformatics. I am currently at the verge of transitioning to a fully Computational career. I believe this program will provide me with  the best platform to practice my acquired Computational skills.

**Comment by karegapauline** [comment]
> 

You have been selected for the Open Science in Africa project. We think your skills will be better suited in that project given that it has data analysis components and requires a lot of coding skills. Let us know if this is of interest to you.

**Comment by karegapauline** [comment]
> > 
> 
> You have been selected for the Open Science in Africa project. We think your skills will be better suited in that project given that it has data analysis components and requires a lot of coding skills. Let us know if this is of interest to you.

**Comment by karegapauline** [comment]
Dear @OduorBetty, @glado718, @cyrille88 , @Gatheru-rose , @Suenjuki and @mudiboevans , welcome to the Viral Analysis mini project team. Kindly respond by sending an email to bioinformaticshubofkenya@gmail.com confirming your acceptance to this invite. 
We look forward to hearing from you. 😃

**Comment by otenga-bit** [comment]
Thnk you so much. I am glad to be part of this project.

**Comment by Oronda** [comment]
Issokay Pauline i'm still interested in the open science project in Africa.
Thank you for the opportunity.

**Comment by EddyKE-hub** [comment]
I am an MSc  student pursuing MSc Molecular Medicine. My project was titled 'Molecular characterization of dengue outbreak virus and their cyto-response to natural plant products'. I have great interest in learning about bioinformatics so that I can have the skills to understand and process my data. Furthermore, I had a attended the H3ABioNet Introduction to Bioinformatics training which was held at ICIPE where I learnt a lot. Participating in this mini-project will greatly improve my knowledge in performing bioinformatic procedures on a real project. More importantly, it will enable me to share my skills and knowledge with the scientific world such as ICIPE and KEMRI. I look forward to hearing from you.

**Comment by Rissy2021** [comment]
Thank you for the opportunity.  Looking forward to a great learning experience.


________________________________

**Comment by JGisaina** [comment]
Thanks for the opporrunity.
I confrim my participation

**Comment by florahnaks** [comment]
Thank you so much for the opportunity,
I confirm my acceptance.

Florence.

**Comment by EddyKE-hub** [comment]
Thank you for accepting me. I confirm my attendance.

**Comment by karegapauline** [comment]
@EddyKE-hub, I believe you commented on the issue after the deadline?
You haven't been assigned any project

**Comment by karegapauline** [comment]
@OduorBetty, @glado718, @cyrille88 , @Gatheru-rose , @Suenjuki and @mudiboevans

Congratulations. You have been selected to participate in the 3rd Phase of BOSS events: Viral Mini project/Metagenomics/Open science/ Data Handbook/Plant genomics. We are inviting you for a virtual meeting on 1st December 2021 at 1600hrs to 1700hrs with the following agenda:

1. Introduction of Participants

2. Meeting up with your respective mentors

3. Time and Deadlines

4. Selecting mini project team leads

5. Discuss on the way forward

AoB


This is a mandatory meeting, so kindly join on time. Find the link to the zoom meeting below. We look forward to seeing you.



BHKI is inviting you to a scheduled Zoom meeting.

Topic: BOSS Mini Projects Introduction meeting
Time: Dec 1, 2021 04:00 PM Nairobi

Join Zoom Meeting
https://us02web.zoom.us/j/86411432009?pwd=d0h0dVhUSGZoL3VNM2dPYktnbXR2QT09

Meeting ID: 864 1143 2009
Passcode: 611959

Warm Regards,

David Kiragu
On behalf of the BHKi and Open ScienceKE teams
