### ISSUE TITLE
Interest for viral_analysis miniproject

### ISSUE THREAD

**Issue by glado718** [bioinformatics-hub-ke/BOSS-miniprojects#8]
Doing viral analysis project using bioinformatics tools  and pipeline will give me a platform to exercise and showcase my skills in the field of bioinformatics. I was also  recently  involved in drafting a manuscript for codeathon project entitled the genetic diversity of HIV-1 strains in Africa which used similar approaches. Hence, doing this project will help me practice and acquire skills that will be of great help in my career as a bioinformatician.

**Comment by karegapauline** [comment]
Hi @glado718 . I've moved this issue to the viral analysis project as a comment so that it's not overlooked

**Comment by glado718** [comment]
No problem, thank you
