### ISSUE TITLE
Metagenomics mini project

### ISSUE THREAD

**Issue by Marthariv** [bioinformatics-hub-ke/BOSS-miniprojects#9]
I am interested in gaining metagenomics data analysis skills . This metagenomic mini project present a great opportunity to achieve this

**Comment by karegapauline** [comment]
@Marthariv , I will close this issue and move this comment to the metagenomics issue so that it is not missed.

**Comment by Marthariv** [comment]
It ok please moveI appreciate

Sent from Yahoo Mail on Android 
 
  On Wed, 24 Nov 2021 at 15:17, ***@***.***> wrote:   


@Marthariv , I will close this issue and move this comment to the metagenomics issue so that it is not missed.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
